"""empty message

Revision ID: 1ac6a3ffcd96
Revises: b7acdbacbb43
Create Date: 2020-02-04 23:56:50.586974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac6a3ffcd96'
down_revision = 'b7acdbacbb43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
                    sa.Column('uid', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('flag', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
